name: macOS Build
on:
  push:
    branches:
      - master
    tags:
      - "*"
jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node: ["12"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - uses: actions/upload-artifact@v2
        name: Upload DMG
        with:
          name: WeakAuras-Companion-CI-dmg
          path: dist_electron/*.dmg
